name: RunsafeAccounts
main: no.runsafe.accounts.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: A plug-in to link the RunsafeAccounts from website to server
commands:
  account:
    description: Shows available commands for runsafe accounts
